framework:
    messenger:
        failure_transport: failed
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        transports:
            sync: 'sync://'
            failed: 'doctrine://default?queue_name=failed'
