name: pok-sezan
recipe: symfony
config:
  php: '8.1'
  composer_version: '2.0.7'
  via: nginx
  webroot: public
  database: mysql
  cache: redis
  xdebug: false
services:
  db2: # @see https://docs.devwithlando.io/tutorials/mysql.html#configuration
    type: mysql
    creds:
      user: symfony
      password: symfony
      database: symfony_test
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
  php-cs-fixer:
    service: appserver
    description: "Run php cs fix on diff files"
    cmd: cd /app && php ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --path-mode=intersection --diff --using-cache=no -- $(git diff --cached --name-only --diff-filter=ACM -- '*.php')
